# Generated by Django 5.0 on 2023-12-20 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(choices=[('g', 'gram'), ('kg', 'kilogram'), ('ozm', 'ounce (mass)'), ('lb', 'pound'), ('l', 'liter'), ('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('oz', 'ounce (fluid)'), ('c', 'cup'), ('qt', 'quart'), ('gal', 'gallon'), ('ea', 'each'), ('pk', 'pack'), ('cs', 'case')], default='ea', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('yield_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeBuildItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('g', 'gram'), ('kg', 'kilogram'), ('ozm', 'ounce (mass)'), ('lb', 'pound'), ('l', 'liter'), ('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('oz', 'ounce (fluid)'), ('c', 'cup'), ('qt', 'quart'), ('gal', 'gallon'), ('ea', 'each'), ('pk', 'pack'), ('cs', 'case')], default='ea', max_length=4)),
                ('build_ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='recipes.ingredient')),
                ('build_recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='recipes.recipe')),
                ('master_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
