# Generated by Django 5.0 on 2023-12-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredient_created_alter_ingredient_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
